name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  IMAGE_REGISTRY: charlessantarosa/ws-recommender
  IMAGE_TAG: ${{ github.sha }}
jobs:
  ws-recommender-prod:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Login Registry DockerHub
        id: login-gitlab
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:          
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}        
        
      - name: Build, tag, and push image to Gitlab.com
        id: build-image        
        run: |
          docker build -t $IMAGE_REGISTRY:$IMAGE_TAG .
          docker push $IMAGE_REGISTRY:$IMAGE_TAG
          echo "::set-output name=image::$IMAGE_REGISTRY:$IMAGE_TAG"

      - name: Deploy container to VM/AWS
        uses: ironhalik/docker-over-ssh-action@v1
        with:
          user: ubuntu
          host: ec2-3-12-154-140.us-east-2.compute.amazonaws.com
          key: ${{ secrets.SSH_PRIVATE_KEY }}          
          script: |
            docker rm -f recommender | true
            docker run --privileged -p 80:3000 --name recommender --restart unless-stopped -d $IMAGE_REGISTRY:$IMAGE_TAG
            echo "Deploy Recommender System [ OK ]"
