name: CI
on:  

  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ws-recommender-prod:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Login Registry Gitlab.com
        id: login-gitlab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
        env:
          IMAGE_REGISTRY: registry.gitlab.com/charles.santarosa.br/miscelaneos/uea-recommender          
          IMAGE_TAG: ${{ github.sha }}
        
      - name: Build, tag, and push image to Gitlab.com
        id: build-image        
        run: |
          docker build -t $IMAGE_REGISTRY:$IMAGE_TAG .
          docker push $IMAGE_REGISTRY:$IMAGE_TAG
          echo "::set-output name=image::$IMAGE_REGISTRY:$IMAGE_TAG"

      - name: Deploy container to VM/AWS
        uses: ironhalik/docker-over-ssh-action@v1
        with:
          user: ubuntu
          host: ec2-3-12-154-140.us-east-2.compute.amazonaws.com
          key: ${{ secrets.SSH_PRIVATE_KEY }}          
          script: |
            docker run -d -p 80:3000 $IMAGE_REGISTRY:$IMAGE_TAG
            echo "Deploy Recommender System [ OK ]"
